name = "backorder-domain-monitor"
main = "src/index.ts"
compatibility_date = "2025-02-01"
workers_dev = true

[triggers]
crons = ["0 * * * *"] # hourly (24x/day)

[[d1_databases]]
binding = "DB"
database_name = "backorder_d1"
database_id = "c91b2c14-9a64-4e15-b36e-4203ca2b8baa"
migrations_dir = "migrations"
